# Generated by Django 3.0.4 on 2020-03-15 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField()),
                ('sunday', models.CharField(max_length=3)),
                ('monday', models.CharField(max_length=3)),
                ('tuesday', models.CharField(max_length=3)),
                ('wednesday', models.CharField(max_length=3)),
                ('thursday', models.CharField(max_length=3)),
                ('friday', models.CharField(max_length=3)),
                ('saturday', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('area', models.CharField(choices=[('TZAF', 'צפון'), ('JERU', 'ירושלים והסביבה'), ('MERK', 'מרכז'), ('YEHU', 'יהודה ושומרון'), ('DARO', 'דרום')], max_length=10)),
                ('phone_number', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('available_saturday', models.BooleanField()),
                ('notes', models.CharField(max_length=200)),
                ('moving_way', models.CharField(choices=[('CAR', 'רכב'), ('PUBL', 'תחב"צ'), ('FOOT', 'רגלית')], max_length=20)),
                ('hearing_way', models.CharField(choices=[('FB_INST', 'פייסבוק ואינסטגרם'), ('WHTSP', 'ווצאפ'), ('RAD_TV', 'רדיו וטלוויזיה'), ('OTHR', 'אחר')], max_length=20)),
                ('creation_date', models.DateTimeField()),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.City')),
                ('languages', models.ManyToManyField(to='client.Language')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.VolunteerSchedule')),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('BUYIN', 'קניות\\איסוף'), ('MEDICI', 'תרופות'), ('HOME_HEL', 'עזרה בבית'), ('PHONE_HEL', 'תמיכה טלפונית'), ('OTHER', 'אחר')], max_length=20)),
                ('type_text', models.CharField(max_length=5000)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.City')),
            ],
        ),
    ]
