# Generated by Django 3.0.4 on 2020-03-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
