# Generated by Django 3.0.4 on 2020-03-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200326_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_type',
            field=models.CharField(choices=[('NIEGHBORHOOD_COORDINATOR', 'רכז שכונה'), ('CITY_COORDINATOR', 'רכז עיר'), ('STAFF', 'מטה'), ('HAMAL', 'חמל'), ('PROJECT', 'פרויקט'), ('CHILD_CARE', 'משפחתון'), ('MISSIONS', 'משימות')], default='MISSIONS', max_length=200),
        ),
    ]
