# Generated by Django 3.0.4 on 2020-03-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_volunteer_volunteer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
