# Generated by Django 3.0.4 on 2020-03-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_volunteercertificate'),
        ('client', '0002_auto_20200327_1432'),
        ('client', '0004_auto_20200327_0549'),
    ]

    operations = [
    ]
