# Generated by Django 3.0.4 on 2020-03-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_merge_20200327_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
