# Generated by Django 3.0.4 on 2020-03-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_merge_20200327_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='notes',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
