# Generated by Django 3.0.4 on 2020-03-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20200328_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_type',
            field=models.CharField(choices=[('NIEGHBORHOOD_COORDINATOR', 'רכז שכונה'), ('CITY_COORDINATOR', 'רכז עיר'), ('STAFF', 'מטה'), ('HAMAL', 'חמל'), ('PROJECT', 'פרויקט'), ('CHILD_CARE', 'משפחתון'), ('MISSIONS', 'משימות'), ('AGRICULTURE', 'חקלאות')], default='MISSIONS', max_length=200),
        ),
    ]
