# Generated by Django 3.0.4 on 2020-03-30 09:42

import client.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20200328_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='tz_number',
            field=models.CharField(blank=True, max_length=11, validators=[client.validators.id_number_validator]),
        ),
    ]
