# Generated by Django 3.0.4 on 2020-03-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20200329_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='age',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
