# Generated by Django 3.0.4 on 2020-03-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20200329_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
