# Generated by Django 3.0.4 on 2020-03-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20200402_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='full_name',
        ),
    ]
