# Generated by Django 3.0.4 on 2020-04-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20200330_1711'),
        ('client', '0006_auto_20200328_2346'),
        ('client', '0007_auto_20200329_1519'),
    ]

    operations = [
    ]
