# Generated by Django 3.0.4 on 2020-04-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_merge_20200402_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='age',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
