# Generated by Django 3.0.4 on 2020-04-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_remove_volunteer_full_name'),
        ('client', '0006_auto_20200328_2346'),
    ]

    operations = [
    ]
