# Generated by Django 3.0.4 on 2020-04-02 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_volunteercertificate_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteercertificate',
            old_name='image',
            new_name='_image',
        ),
    ]
