# Generated by Django 3.0.4 on 2020-03-30 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20200330_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequest',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='last_name',
        ),
    ]
