# Generated by Django 3.0.4 on 2020-04-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20200402_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
