# Generated by Django 3.0.4 on 2020-04-02 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_auto_20200402_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='helping_volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Volunteer'),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerschedule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
