# Generated by Django 3.0.4 on 2020-04-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20200402_1224'),
        ('client', '0010_merge_20200402_1249'),
    ]

    operations = [
    ]
