# Generated by Django 3.0.4 on 2020-04-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_auto_20200402_1637'),
        ('client', '0010_auto_20200402_1040'),
    ]

    operations = [
    ]
