# Generated by Django 3.0.4 on 2020-04-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_merge_20200403_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='request_reason',
            field=models.CharField(choices=[('ISOLATION', 'בידוד'), ('HIGH_RISK_GROUP', 'קבוצת סיכון גבוהה'), ('OTHER', 'אחר')], default='OTHER', max_length=25),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
