# Generated by Django 3.0.4 on 2020-04-06 21:38

import client.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20200406_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(choices=[('MALE', 'זכר'), ('FEMALE', 'נקבה'), ('OTHER', 'מגדר אחר')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='location_address_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='location_address_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='wanted_assignments',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('FOOD', 'חלוקת מזון'), ('MEDICINES', 'משלוח תרופות'), ('STAFF', 'הסעות'), ('TRANSPORTATION', 'סיוע לעובדים חיוניים'), ('TELEPHONE SUPPORT', 'תמיכה טלפונית'), ('CHILD_CARE', 'עזרה במשפחתונים'), ('OTHER', 'אחר')], default=1, max_length=70),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='week_assignments_capacity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='areas',
            field=models.ManyToManyField(blank=True, to='client.Area'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='available_saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='guiding',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='hearing_way',
            field=models.CharField(blank=True, choices=[('FB_INST', 'פייסבוק ואינסטגרם'), ('WHTSP', 'ווצאפ'), ('RAD_TV', 'רדיו וטלוויזיה'), ('OTHR', 'אחר')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='keep_mandatory_worker_children',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='moving_way',
            field=models.CharField(choices=[('BIKE', 'אופניים'), ('SCOOTER', 'קטנוע'), ('AUTOMOBILE', 'מכונית'), ('PUBL', 'תחבורה ציבורית'), ('FOOT', 'רגלית')], max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='notes',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_type',
            field=models.CharField(choices=[('NIGHBORHOOD_COORDINATOR', 'רכז שכונה'), ('CITY_COORDINATOR', 'רכז עיר'), ('STAFF', 'מטה'), ('HAMAL', 'חמל'), ('PROJECT', 'פרויקט'), ('CHILD_CARE', 'משפחתון'), ('AGRICULTURE', 'חקלאות'), ('MISSIONS', 'משימות')], default='MISSIONS', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ParentalConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_id', models.CharField(max_length=9, validators=[client.validators.id_number_validator])),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.Volunteer')),
            ],
        ),
    ]
