# Generated by Django 3.0.4 on 2020-04-06 17:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20200406_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='location_address_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='location_address_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='sex',
            field=models.CharField(choices=[('MALE', 'זכר'), ('FEMALE', 'נקבה')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='wanted_assignments',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NIGHBORHOOD_COORDINATOR', 'רכז שכונה'), ('CITY_COORDINATOR', 'רכז עיר'), ('STAFF', 'מטה'), ('HAMAL', 'חמל'), ('PROJECT', 'פרויקט'), ('CHILD_CARE', 'משפחתון'), ('AGRICULTURE', 'חקלאות'), ('MISSIONS', 'משימות')], default=1, max_length=92),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='week_assignments_capacity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='moving_way',
            field=models.CharField(choices=[('BIKE', 'אופניים'), ('SCOOTER', 'קטנוע'), ('AUTOMOBILE', 'רכב'), ('PUBL', 'תחבצ'), ('FOOT', 'רגלית')], max_length=20),
        ),
        migrations.CreateModel(
            name='ParentalConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_id', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[0-9]{9}$')])),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.Volunteer')),
            ],
        ),
    ]
