# Generated by Django 3.0.4 on 2020-04-07 08:01

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_auto_20200407_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'זכר'), ('FEMALE', 'נקבה'), ('OTHER', 'מגדר אחר')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='moving_way',
            field=models.CharField(choices=[('BIKE', 'אופניים'), ('SCOOTER', 'קטנוע'), ('CAR', 'מכונית'), ('PUBL', 'תחבורה ציבורית'), ('FOOT', 'רגלית')], max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='wanted_assignments',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('FOOD', 'חלוקת מזון'), ('MEDICINES', 'משלוח תרופות'), ('STAFF', 'הסעות'), ('TRANSPORTATION', 'סיוע לעובדים חיוניים'), ('TELEPHONE SUPPORT', 'תמיכה טלפונית'), ('CHILD_CARE', 'עזרה במשפחתונים'), ('OTHER', 'אחר')], default=(('FOOD', 'חלוקת מזון'), ('MEDICINES', 'משלוח תרופות'), ('STAFF', 'הסעות'), ('TRANSPORTATION', 'סיוע לעובדים חיוניים'), ('TELEPHONE SUPPORT', 'תמיכה טלפונית'), ('CHILD_CARE', 'עזרה במשפחתונים'), ('OTHER', 'אחר')), max_length=70),
        ),
    ]
