# Generated by Django 3.0.4 on 2020-04-06 20:49

import client.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_auto_20200406_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentalconsent',
            name='parent_id',
            field=models.CharField(max_length=9, validators=[client.validators.id_number_validator]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='areas',
            field=models.ManyToManyField(blank=True, to='client.Area'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='available_saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='guiding',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='hearing_way',
            field=models.CharField(blank=True, choices=[('FB_INST', 'פייסבוק ואינסטגרם'), ('WHTSP', 'ווצאפ'), ('RAD_TV', 'רדיו וטלוויזיה'), ('OTHR', 'אחר')], max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='languages',
            field=models.ManyToManyField(blank=True, to='client.Language'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='moving_way',
            field=models.CharField(choices=[('BIKE', 'אופניים'), ('SCOOTER', 'קטנוע'), ('AUTOMOBILE', 'מכונית'), ('PUBL', 'תחבורה ציבורית'), ('FOOT', 'רגלית')], max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='neighborhood',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='notes',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='organization',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='wanted_assignments',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('FOOD', 'חלוקת מזון'), ('MEDICINES', 'משלוח תרופות'), ('STAFF', 'הסעות'), ('TRANSPORTATION', 'סיוע לעובדים חיוניים'), ('TELEPHONE SUPPORT', 'תמיכה טלפונית'), ('CHILD_CARE', 'עזרה במשפחתונים'), ('OTHER', 'אחר')], default=1, max_length=70),
        ),
    ]
