# Generated by Django 3.0.4 on 2020-04-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_auto_20200407_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='request_reason',
            field=models.CharField(choices=[('ISOLATION', 'בידוד'), ('HIGH_RISK_GROUP', 'קבוצת סיכון גבוהה'), ('OTHER', 'אחר')], default='OTHER', max_length=25),
        ),
    ]
