# Generated by Django 3.0.4 on 2020-04-07 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_auto_20200407_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Area'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='guiding',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_type',
            field=models.CharField(blank=True, choices=[('NIGHBORHOOD_COORDINATOR', 'רכז שכונה'), ('CITY_COORDINATOR', 'רכז עיר'), ('STAFF', 'מטה'), ('HAMAL', 'חמל'), ('PROJECT', 'פרויקט'), ('CHILD_CARE', 'משפחתון'), ('AGRICULTURE', 'חקלאות'), ('MISSIONS', 'משימות')], default='MISSIONS', max_length=200, null=True),
        ),
    ]
