# Generated by Django 3.0.4 on 2020-04-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_auto_20200407_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentalconsent',
            name='parent_id',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='tz_number',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
