# Generated by Django 3.0.4 on 2020-04-07 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_auto_20200407_1728'),
        ('client', '0019_auto_20200407_1819'),
        ('client', '0019_auto_20200407_1745'),
    ]

    operations = [
    ]
