# Generated by Django 3.0.4 on 2020-04-07 20:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_merge_20200407_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='wanted_assignments',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('FOOD', 'חלוקת מזון'), ('MEDICINES', 'משלוח תרופות'), ('STAFF', 'סיוע לעובדים חיוניים'), ('TRANSPORTATION', 'הסעות'), ('TELEPHONE SUPPORT', 'תמיכה טלפונית'), ('CHILD_CARE', 'עזרה במשפחתונים'), ('OTHER', 'אחר')], default=['FOOD', 'MEDICINES', 'STAFF', 'TRANSPORTATION', 'TELEPHONE SUPPORT', 'CHILD_CARE', 'OTHER'], max_length=70),
        ),
    ]
