# Generated by Django 3.0.4 on 2020-04-07 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_helprequest_request_reason'),
        ('client', '0020_merge_20200407_2229'),
    ]

    operations = [
    ]
