# Generated by Django 3.0.4 on 2020-04-11 15:36

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_merge_20200408_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentalconsent',
            name='volunteer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parental_consent', to='client.Volunteer'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='wanted_assignments',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('FOOD', 'חלוקת מזון'), ('MEDICINES', 'משלוח תרופות'), ('STAFF', 'סיוע לעובדים חיוניים'), ('TRANSPORTATION', 'הסעות'), ('TELEPHONE SUPPORT', 'תמיכה טלפונית'), ('CHILD_CARE', 'עזרה במשפחתונים'), ('OTHER', 'אחר')], default=['FOOD', 'MEDICINES', 'STAFF', 'TRANSPORTATION', 'TELEPHONE SUPPORT', 'CHILD_CARE', 'OTHER'], max_length=70),
        ),
    ]
