# Generated by Django 3.0.4 on 2020-04-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0024_auto_20200416_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='location_address_x',
            new_name='location_latitude',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='location_address_y',
            new_name='location_longitude',
        ),
        migrations.AddField(
            model_name='helprequest',
            name='location_latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='location_longitude',
            field=models.FloatField(default=0),
        ),
    ]
