# Generated by Django 3.0.4 on 2020-04-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_auto_20200417_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='location_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='location_failed',
            field=models.BooleanField(default=False),
        ),
    ]
