# Generated by Django 3.0.4 on 2020-04-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0026_auto_20200417_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='moving_way',
            field=models.CharField(blank=True, choices=[('BIKE', 'אופניים'), ('SCOOTER', 'קטנוע'), ('CAR', 'מכונית'), ('PUBL', 'תחבורה ציבורית'), ('FOOT', 'רגלית')], max_length=20, null=True),
        ),
    ]
