# Generated by Django 3.0.4 on 2020-04-19 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0028_auto_20200417_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerFreeze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False, null=True)),
                ('updated_date', models.DateTimeField(editable=False, null=True)),
                ('expiration_date', models.DateField(db_index=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezes', to='client.Volunteer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
