# Generated by Django 3.0.7 on 2020-09-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0029_volunteerfreeze'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerfreeze',
            name='freeze_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
