name: CI
on:
  pull_request:
    branches:
        - master
        - develop

jobs:
  code-style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: pycodestyle
      uses: ./.github/actions/code-style
      with:
          comment-message: "PycodeStyle:"

    - name: comment PR
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          msg: Pre-${{ steps.pycodestyle.outputs.COMMENT }}
