name: CI
on:
  pull_request:
    branches:
        - master
        - develop

jobs:
  code-style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: pycodestyle
      uses: ./.github/actions/code-style
      with:
          comment-message: "PycodeStyle:"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
